packages:
  - "."
  - "frontend"
  - "keeper"
  - "packages/*"

allowBuilds:
  "@reown/appkit": true
  bigint-buffer: true
  bufferutil: true
  esbuild: true
  keccak: true
  protobufjs: true
  secp256k1: true
  unrs-resolver: true
  utf-8-validate: true

overrides:
  ws: 8.21.0
